# This is a basic workflow to help you get started with Actions

name: testworkflow

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print some
        run: echo "Hello"
      - name: Print some
        run: |
          echo "Bye-Bye"
          echo "Bye-Bye"
          echo "Bye-Bye"
